---
- hosts: all
  become: yes
  tasks:
    - name: unistall git
      apt:  
        name: git
        state: absent
    - name: unistall tree
      apt:
        name: tree
        state: absent
    - name: unistall wget
      apt:
        name: wget
        state: absent        
