---
- hosts: mywebserver
  become: yes
  tasks:
    - name: install git 
      apt:  
        name: git
        state: present
    - name: install tree
      apt:
        name: treeee
        state: present
      ignore_errors: yes  
    - name: install apache2
      apt:
        name: apache2
        state: present
