---
- hosts: mywebserver
  become: yes
  tasks:
    - name: create group test  
      group:
        name: test
        state: present
    - name: create user test 
      user:
        name: test
        group: test
        shell: /bin/false
        home: /opt/test
        state: present
