---
- name: update group permission
  file:
    path: /opt/tomcat
    group: tomcat
    recurse: yes
    state: directory

- name: update mod of /opt/tomcat/conf
  file:
    path: /opt/tomcat/conf
    group: tomcat
    mode: g+xr
    recurse: yes
    state: directory 

- name: update owner for webapps
  file:
    path: /opt/tomcat/webapps
    ownwer: tomcat
    recurse: yes
    state: directory  

- name: update owner for work
  file:
    path: /opt/tomcat/work
    ownwer: tomcat
    recurse: yes
    state: directory 

- name: update owner for temp
  file:
    path: /opt/tomcat/temp
    ownwer: tomcat
    recurse: yes
    state: directory 

- name: update owner for logs
  file:
    path: /opt/tomcat/logs
    ownwer: tomcat
    recurse: yes
    state: directory      
